### ISSUE TITLE
Censorship

### ISSUE THREAD

**Issue by sunkevin101** [Cassie07/PathOmics#12]
Hello, in PathOmics/PathOmics/data_loading_utils/load_files.py line117. Why is censorship == '1:PROGRESSION' set to 0? 
It seems to contradict the appendix "where cj = 0 means patient passed away during Tj and cj = 1 means patient lived after Tj ."

**Comment by Cassie07** [comment]
Hi @KevinSUN-Mac, thanks for your interest in our study. We sincerely thank you for helping us realize that we mistakenly uploaded a previous version of the code from the server. 

We actually used "OS_STATUS" to determine the censorship instead of "PFS_STATUS". Hence, it should be censorship == '1:DECEASED' set to 0, while censorship == '0:LIVING'  set to 1. These are consistent with the details we provided in the Appendix.

I have updated the related codes.

Please feel free to contact me if you have any questions or concerns.

Bests,
Kexin

**Comment by sunkevin101** [comment]
OK, @Cassie07, thanks for your reply. Now I understand better about your PathOmics code.

Thank you again!

Yours sincerely, 
Kevin
