### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by gaogehan** [Cassie07/PathOmics#5]
I try to run the bash_main.py on COAD in different CUDA  enviroment. But, I encounter the same cuda error.

> ../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

![image](https://github.com/Cassie07/PathOmics/assets/112455033/4ff3670c-28a9-46f5-93fd-3eedd2a2a4f2)

**Comment by Cassie07** [comment]
@gaogehan Hello! Thanks for your interest in our study. I have cloned this GitHub repo and run bash_main.py under my environment. The code works well, and I did not get the same CUDA error as yours. My current PyTorch version is 2.0.1, and the CUDA version is 12.2. Have you made any modifications to the data or network architecture?

I tried to help you find solutions to similar issues [issue15](https://github.com/IrvingMeng/MagFace/issues/15). Hopefully, it will be helpful for you. 

Bests,
Kexin

**Comment by gaogehan** [comment]
Thank you for your reply. I have made efforts to resolve the issue based on your advice, but unfortunately, it remains unresolved. The program runs smoothly during the pre-training stage, but encounters CUDA index error during the fine-tuning stage. I haven't made any modifications to the relevant code. I have verified that my input features data are correct. Therefore, I suspect there may be an issue with my genomics data (It seems that the fine-tuning stage uses more genomic data.). Could you please provide fold coadread_tcga_pan_can_atlas_2018 ? I sincerely appreciate your help.

**Comment by Cassie07** [comment]
@gaogehan Hello! Thanks for the efforts! 'coadread_tcga_pan_can_atlas_2018' is the public data; I downloaded it from cBioPortal. It is too large to be uploaded to the GitHub repo; please download it to your local server via the attached [link](https://www.cbioportal.org/study/summary?id=coadread_tcga_pan_can_atlas_2018). 

Also, I believe that both pretraining and finetuning use the same genomics data. So that's weird that the same data works well on pretraining while getting the CUDA error in finetuning. Let's keep in touch to figure it out. Please feel free to let me know if you have any further questions or need anything.

**Comment by gaogehan** [comment]
Thank you for your response. This is indeed a bizarre error. I attempt to run the code on TCGA-COAD and TCGA-READ. The pre-training and fine-tuning processes went smoothly. However, when running the code solely on TCGA-COAD, I encounter CUDA error during the fine-tuning stage. Thank you for following up, and I will continue to search for a solution.
![image](https://github.com/Cassie07/PathOmics/assets/112455033/3281dbc1-bae7-4179-a809-f68a389102a0)

**Comment by Cassie07** [comment]
@gaogehan Good to know that! Please feel free to contact me if you have further questions.
